/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_giorgi_movierecognition_controller_ComputeHashThread */

#ifndef _Included_com_example_giorgi_movierecognition_controller_ComputeHashThread
#define _Included_com_example_giorgi_movierecognition_controller_ComputeHashThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_giorgi_movierecognition_controller_ComputeHashThread_MIN_PRIORITY
#define com_example_giorgi_movierecognition_controller_ComputeHashThread_MIN_PRIORITY 1L
#undef com_example_giorgi_movierecognition_controller_ComputeHashThread_NORM_PRIORITY
#define com_example_giorgi_movierecognition_controller_ComputeHashThread_NORM_PRIORITY 5L
#undef com_example_giorgi_movierecognition_controller_ComputeHashThread_MAX_PRIORITY
#define com_example_giorgi_movierecognition_controller_ComputeHashThread_MAX_PRIORITY 10L
/*
 * Class:     com_example_giorgi_movierecognition_controller_ComputeHashThread
 * Method:    getFrameHash
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_giorgi_movierecognition_controller_ComputeHashThread_getFrameHash
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
